### ISSUE TITLE
Bug/NRE when used along with Factorissimo2

### ISSUE THREAD

**Issue by sharkck** [bthaase/Factorio-Microwave#1]
When you enter a Factorissimo2 warehouse/factory, the game crashes with the following error (Removing Microwave Transmission fixes the problem and nothing crashes):

The mod Factorissimo2 caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Factorissimo2::on_tick (ID 0)
The mod Microwave Transmission caused a non-recoverable error.
Please report this error to the mod author.

Error while running event camedo-microwave::on_player_changed_surface (ID 51)
__camedo-microwave__/stdlib/table.lua:90: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__camedo-microwave__/stdlib/table.lua:90: in function 'each'
	__camedo-microwave__/control.lua:324: in function 'reset_targets'
	__camedo-microwave__/control.lua:346: in function <__camedo-microwave__/control.lua:346>
stack traceback:
	__Factorissimo2__/control.lua:1037: in function 'teleport_player_safely'
	__Factorissimo2__/control.lua:1043: in function 'enter_factory'
	__Factorissimo2__/control.lua:1071: in function 'teleport_players'
	__Factorissimo2__/control.lua:1163: in function <__Factorissimo2__/control.lua:1133>
stack traceback:
	[C]: in function 'teleport'
	__Factorissimo2__/control.lua:1037: in function 'teleport_player_safely'
	__Factorissimo2__/control.lua:1043: in function 'enter_factory'
	__Factorissimo2__/control.lua:1071: in function 'teleport_players'
	__Factorissimo2__/control.lua:1163: in function <__Factorissimo2__/control.lua:1133>

**Comment by sharkck** [comment]
[factorio-previous.log](https://github.com/bthaase/Factorio-Microwave/files/4006638/factorio-previous.log)

**Comment by bthaase** [comment]
Thank you for the report! Issue was reproduced and promptly squashed, i'll have Version 1.0.2 up on the mod portal and releases page shortly.
