### ISSUE TITLE
Mod does not work on vehicle grids.

### ISSUE THREAD

**Issue by buffog** [bthaase/Factorio-Microwave#2]
Particularly on the ones added by [Krastorio 2](https://mods.factorio.com/mod/Krastorio2) and [Vehicle Grid](https://mods.factorio.com/mod/VehicleGrid).
Probably something with equipment categories, as it seems like Rectennas are not recognised as vehicle equipment.

**Comment by bthaase** [comment]
Sorry for the long sleep on this, being resolved in version 1.0.6
